import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';

interface LanguageContextProps {
  language: string;
  setLanguage: (language: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

interface LanguageProviderProps {
  children: React.ReactNode;
}

const translations = {
  en: {
    "uploadPdfFile": "Upload PDF File",
    "documentAnalysis": "Document Analysis",
    "exportAnalysis": "Export Analysis",
    "exportDescription": "Export the analysis results to a PDF file for easy sharing and archiving.",
    "exportToPdf": "Export to PDF",
    "noDataToExport": "No data available to export.",
    "exportSuccess": "Analysis exported successfully!",
    "exportError": "Error exporting analysis.",
    "fileInformation": "File Information",
    "fileName": "File Name",
    "fileSize": "File Size",
    "wordCount": "Word Count",
    "documentSummary": "Document Summary",
    "noSummaryAvailable": "No summary available for this document.",
    "sentimentAnalysis": "Sentiment Analysis",
    "overallSentiment": "Overall Sentiment",
    "sentimentDistribution": "Sentiment Distribution",
    "positive": "Positive",
    "neutral": "Neutral",
    "negative": "Negative",
    "keyPhrases": "Key Phrases",
    "phrase": "Phrase",
    "sentiment": "Sentiment",
    "frequency": "Frequency",
    "themeAnalysisTitle": "Theme Analysis",
    "theme": "Theme",
    "score": "Score",
    "mentions": "Mentions",
    "emotionalTones": "Emotional Tones",
    "emotion": "Emotion",
    "occurrences": "Occurrences",
    "generatedOn": "Generated on",
    "page": "Page",
    "of": "of",
    "documentAnalysisReport": "Document Analysis Report",
    "latentEmotionalAnalysisTab": "Latent Emotional Analysis",
    "overviewTab": "Overview",
    "timelineTab": "Timeline",
    "themesTab": "Themes",
    "keywordsTab": "Keywords",
    "latentEmotionalAnalysis": "Latent Emotional Analysis",
    "resetView": "Reset View",
    "searchWordsOrEmotions": "Search words or emotions...",
    "searchWords": "Search words...",
    "noResultsFound": "No results found.",
    "hoverOrClick": "Hover over or click on a point to see more details.",
    "selected": "Selected",
    "noDataTabName": "No data available for {tabName} tab.",
    "dataAvailableMissing": "Please ensure that the document analysis is complete and that the necessary data is available.",
    "wellbeingResources": "Wellbeing Resources",
    "findSupport": "Find Support",
    "helpfulResources": "Here are some resources that you might find helpful:",
    "wordComparison": "Word Comparison",
    "selectAWord": "Select a word to compare",
    "emotionalClusters": "Emotional Clusters",
    "clustersDescription": "Adjust the number of clusters to refine the emotional grouping.",
    "displayingClusters": "Displaying top {count} clusters",
    "documentTextVisualization": "Document Text Visualization",
    "showEmotionalHighlights": "Show Emotional Highlights",
    "hideEmotionalHighlights": "Hide Emotional Highlights",
    "noTextAvailableFromPdf": "No text available from PDF",
  },
  fr: {
    "uploadPdfFile": "Télécharger un fichier PDF",
    "documentAnalysis": "Analyse de Document",
    "exportAnalysis": "Exporter l'Analyse",
    "exportDescription": "Exporter les résultats de l'analyse vers un fichier PDF pour faciliter le partage et l'archivage.",
    "exportToPdf": "Exporter en PDF",
    "noDataToExport": "Aucune donnée disponible à exporter.",
    "exportSuccess": "Analyse exportée avec succès !",
    "exportError": "Erreur lors de l'exportation de l'analyse.",
    "fileInformation": "Informations sur le Fichier",
    "fileName": "Nom du Fichier",
    "fileSize": "Taille du Fichier",
    "wordCount": "Nombre de Mots",
    "documentSummary": "Résumé du Document",
    "noSummaryAvailable": "Aucun résumé disponible pour ce document.",
    "sentimentAnalysis": "Analyse des Sentiments",
    "overallSentiment": "Sentiment Général",
    "sentimentDistribution": "Distribution des Sentiments",
    "positive": "Positif",
    "neutral": "Neutre",
    "negative": "Négatif",
    "keyPhrases": "Expressions Clés",
    "phrase": "Expression",
    "sentiment": "Sentiment",
    "frequency": "Fréquence",
    "themeAnalysisTitle": "Analyse Thématique",
    "theme": "Thème",
    "score": "Score",
    "mentions": "Mentions",
    "emotionalTones": "Tonalités Émotionnelles",
    "emotion": "Émotion",
    "occurrences": "Occurrences",
    "generatedOn": "Généré le",
    "page": "Page",
    "of": "de",
    "documentAnalysisReport": "Rapport d'Analyse de Document",
    "latentEmotionalAnalysisTab": "Analyse Émotionnelle Latente",
    "overviewTab": "Aperçu",
    "timelineTab": "Chronologie",
    "themesTab": "Thèmes",
    "keywordsTab": "Mots-clés",
    "latentEmotionalAnalysis": "Analyse Émotionnelle Latente",
    "resetView": "Réinitialiser la Vue",
    "searchWordsOrEmotions": "Rechercher des mots ou des émotions...",
    "searchWords": "Rechercher des mots...",
    "noResultsFound": "Aucun résultat trouvé.",
    "hoverOrClick": "Survolez ou cliquez sur un point pour voir plus de détails.",
    "selected": "Sélectionné",
    "noDataTabName": "Aucune donnée disponible pour l'onglet {tabName}.",
    "dataAvailableMissing": "Veuillez vous assurer que l'analyse du document est terminée et que les données nécessaires sont disponibles.",
    "wellbeingResources": "Ressources de Bien-être",
    "findSupport": "Trouver du Soutien",
    "helpfulResources": "Voici quelques ressources qui pourraient vous être utiles :",
    "wordComparison": "Comparaison de Mots",
    "selectAWord": "Sélectionnez un mot à comparer",
    "emotionalClusters": "Clusters Émotionnels",
    "clustersDescription": "Ajustez le nombre de clusters pour affiner le regroupement émotionnel.",
    "displayingClusters": "Affichage des {count} principaux clusters",
    "documentTextVisualization": "Visualisation du texte du document",
    "showEmotionalHighlights": "Afficher les surlignages émotionnels",
    "hideEmotionalHighlights": "Masquer les surlignages émotionnels",
    "noTextAvailableFromPdf": "Aucun texte disponible depuis le PDF",
  },
  es: {
    "uploadPdfFile": "Cargar archivo PDF",
    "documentAnalysis": "Análisis de Documento",
    "exportAnalysis": "Exportar Análisis",
    "exportDescription": "Exportar los resultados del análisis a un archivo PDF para facilitar el intercambio y el archivo.",
    "exportToPdf": "Exportar a PDF",
    "noDataToExport": "No hay datos disponibles para exportar.",
    "exportSuccess": "¡Análisis exportado con éxito!",
    "exportError": "Error al exportar el análisis.",
    "fileInformation": "Información del Archivo",
    "fileName": "Nombre del Archivo",
    "fileSize": "Tamaño del Archivo",
    "wordCount": "Conteo de Palabras",
    "documentSummary": "Resumen del Documento",
    "noSummaryAvailable": "No hay resumen disponible para este documento.",
    "sentimentAnalysis": "Análisis de Sentimientos",
    "overallSentiment": "Sentimiento General",
    "sentimentDistribution": "Distribución de Sentimientos",
    "positive": "Positivo",
    "neutral": "Neutral",
    "negative": "Negativo",
    "keyPhrases": "Frases Clave",
    "phrase": "Frase",
    "sentiment": "Sentimiento",
    "frequency": "Frecuencia",
    "themeAnalysisTitle": "Análisis Temático",
    "theme": "Tema",
    "score": "Puntuación",
    "mentions": "Menciones",
    "emotionalTones": "Tonos Emocionales",
    "emotion": "Emoción",
    "occurrences": "Ocurrencias",
    "generatedOn": "Generado en",
    "page": "Página",
    "of": "de",
    "documentAnalysisReport": "Informe de Análisis de Documento",
    "latentEmotionalAnalysisTab": "Análisis Emocional Latente",
    "overviewTab": "Visión General",
    "timelineTab": "Cronología",
    "themesTab": "Temas",
    "keywordsTab": "Palabras Clave",
    "latentEmotionalAnalysis": "Análisis Emocional Latente",
    "resetView": "Restablecer Vista",
    "searchWordsOrEmotions": "Buscar palabras o emociones...",
    "searchWords": "Buscar palabras...",
    "noResultsFound": "No se encontraron resultados.",
    "hoverOrClick": "Pase el ratón o haga clic en un punto para ver más detalles.",
    "selected": "Seleccionado",
    "noDataTabName": "No hay datos disponibles para la pestaña {tabName}.",
    "dataAvailableMissing": "Asegúrese de que el análisis del documento esté completo y de que los datos necesarios estén disponibles.",
    "wellbeingResources": "Recursos de Bienestar",
    "findSupport": "Encontrar Apoyo",
    "helpfulResources": "Aquí hay algunos recursos que podrían ser útiles:",
    "wordComparison": "Comparación de Palabras",
    "selectAWord": "Seleccione una palabra para comparar",
    "emotionalClusters": "Clusters Emocionales",
    "clustersDescription": "Ajuste el número de clusters para refinar la agrupación emocional.",
    "displayingClusters": "Mostrando los {count} principales clusters",
    "documentTextVisualization": "Visualización del texto del documento",
    "showEmotionalHighlights": "Mostrar destacados emocionales",
    "hideEmotionalHighlights": "Ocultar destacados emocionales",
    "noTextAvailableFromPdf": "No hay texto disponible del PDF",
  },
  de: {
    "uploadPdfFile": "PDF-Datei hochladen",
    "documentAnalysis": "Dokumentenanalyse",
    "exportAnalysis": "Analyse exportieren",
    "exportDescription": "Exportieren Sie die Analyseergebnisse in eine PDF-Datei, um sie einfach zu teilen und zu archivieren.",
    "exportToPdf": "Als PDF exportieren",
    "noDataToExport": "Keine Daten zum Exportieren verfügbar.",
    "exportSuccess": "Analyse erfolgreich exportiert!",
    "exportError": "Fehler beim Exportieren der Analyse.",
    "fileInformation": "Dateiinformationen",
    "fileName": "Dateiname",
    "fileSize": "Dateigröße",
    "wordCount": "Wortanzahl",
    "documentSummary": "Dokumentzusammenfassung",
    "noSummaryAvailable": "Keine Zusammenfassung für dieses Dokument verfügbar.",
    "sentimentAnalysis": "Sentimentanalyse",
    "overallSentiment": "Gesamtsentiment",
    "sentimentDistribution": "Sentimentverteilung",
    "positive": "Positiv",
    "neutral": "Neutral",
    "negative": "Negativ",
    "keyPhrases": "Schlüsselbegriffe",
    "phrase": "Begriff",
    "sentiment": "Sentiment",
    "frequency": "Häufigkeit",
    "themeAnalysisTitle": "Themenanalyse",
    "theme": "Thema",
    "score": "Punktzahl",
    "mentions": "Erwähnungen",
    "emotionalTones": "Emotionale Töne",
    "emotion": "Emotion",
    "occurrences": "Vorkommnisse",
    "generatedOn": "Erstellt am",
    "page": "Seite",
    "of": "von",
    "documentAnalysisReport": "Bericht zur Dokumentenanalyse",
    "latentEmotionalAnalysisTab": "Latente emotionale Analyse",
    "overviewTab": "Überblick",
    "timelineTab": "Zeitleiste",
    "themesTab": "Themen",
    "keywordsTab": "Schlüsselwörter",
    "latentEmotionalAnalysis": "Latente emotionale Analyse",
    "resetView": "Ansicht zurücksetzen",
    "searchWordsOrEmotions": "Wörter oder Emotionen suchen...",
    "searchWords": "Wörter suchen...",
    "noResultsFound": "Keine Ergebnisse gefunden.",
    "hoverOrClick": "Bewegen Sie den Mauszeiger über einen Punkt oder klicken Sie darauf, um weitere Details anzuzeigen.",
    "selected": "Ausgewählt",
    "noDataTabName": "Keine Daten für den Tab {tabName} verfügbar.",
    "dataAvailableMissing": "Bitte stellen Sie sicher, dass die Dokumentenanalyse abgeschlossen ist und die erforderlichen Daten verfügbar sind.",
    "wellbeingResources": "Ressourcen für das Wohlbefinden",
    "findSupport": "Unterstützung finden",
    "helpfulResources": "Hier sind einige Ressourcen, die Sie möglicherweise hilfreich finden:",
    "wordComparison": "Wortvergleich",
    "selectAWord": "Wählen Sie ein Wort zum Vergleichen aus",
    "emotionalClusters": "Emotionale Cluster",
    "clustersDescription": "Passen Sie die Anzahl der Cluster an, um die emotionale Gruppierung zu verfeinern.",
    "displayingClusters": "Anzeige der Top-{count}-Cluster",
    "documentTextVisualization": "Dokumenttextvisualisierung",
    "showEmotionalHighlights": "Emotionale Hervorhebungen anzeigen",
    "hideEmotionalHighlights": "Emotionale Hervorhebungen ausblenden",
    "noTextAvailableFromPdf": "Kein Text aus PDF verfügbar",
  },
};

const getNavigatorLanguage = () => {
  if (typeof window === 'undefined') {
    return 'en';
  }
  return navigator.language.slice(0, 2) || 'en';
};

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<string>(() => {
    const storedLanguage = typeof window !== 'undefined' ? localStorage.getItem('language') : null;
    return storedLanguage || getNavigatorLanguage();
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = useCallback((key: string) => {
    const translation = translations[language]?.[key] || translations.en[key] || key;
    return translation;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
