import React, { createContext, useContext, useState, ReactNode } from 'react';

interface Translations {
  [key: string]: string;
}

interface LanguageContextType {
  t: (key: string) => string;
  setLanguage: (lang: string) => void;
  language: string;
}

const translations: Record<string, Translations> = {
  en: {
    "upload": "Upload",
    "darkMode": "Dark Mode",
    "lightMode": "Light Mode",
    "selectFile": "Select File",
    "orDragDrop": "or Drag & Drop",
    "journalEntry": "Journal Entry",
    "perfectLife": "Perfect Life",
    "monthlyReflections": "Monthly Reflections",
    "documentAnalysis": "Document Analysis",
    "selectedFile": "Selected File",
    "noFileSelected": "No file selected",
    "analyzeWithBert": "Analyze with BERT",
    "analyzeWithGemma3": "Analyze with Gemma 3",
    "analysisResults": "Analysis Results",
    "fileName": "File Name",
    "fileSize": "File Size",
    "wordCount": "Word Count",
    "latentEmotionalAnalysisTab": "Latent Emotional Analysis",
    "overviewTab": "Overview",
    "timelineTab": "Timeline",
    "themesTab": "Themes",
    "keywordsTab": "Keywords",
    "latentEmotionalAnalysis": "Latent Emotional Analysis",
    "searchWordsOrEmotions": "Search Words or Emotions",
    "resetView": "Reset View",
    "searchWords": "Search Words",
    "noResultsFound": "No Results Found",
    "hoverOrClick": "Hover or click on a point to see more details",
    "overallSentiment": "Overall Sentiment",
    "positive": "Positive",
    "neutral": "Neutral",
    "negative": "Negative",
    "sentimentDistribution": "Sentiment Distribution",
    "time": "Time",
    "event": "Event",
    "entity": "Entity",
    "sentimentScore": "Sentiment Score",
    "keyPhrase": "Key Phrase",
    "occurrences": "Occurrences",
    "relatedTerms": "Related Terms",
    "visualSearch": "Visual Search",
    "wellbeingResources": "Wellbeing Resources",
    "compareWords": "Compare Words",
    "spatialSimilarity": "Spatial Similarity",
    "sentimentSimilarity": "Sentiment Similarity",
    "emotionalProximity": "Emotional Proximity",
    "sharedKeywords": "Shared Keywords",
    "submitEntry": "Submit Entry",
    "pastEntries": "Past Entries",
    "noPastEntries": "No past entries available.",
    "addToMonthlyReflection": "Add to Monthly Reflection",
    "saveChanges": "Save Changes",
    "daily": "Daily",
    "weekly": "Weekly",
    "monthly": "Monthly",
    "perfectDay": "What does your perfect day look like?",
    "perfectWeek": "What does your perfect week look like?",
    "perfectMonth": "What does your perfect month look like?",
    "journalPrompt": "Write about your day...",
    "journalCache": "Journal Cache",
    "selectEntry": "Select Entry",
    "noDataTabName": "No data available for {tabName} tab.",
    "dataAvailableMissing": "Please ensure that the document analysis is complete to view this content.",
    "selected": "Selected",
    "neutral": "Neutral",
    "selectingComparison": "Selecting comparison point...",
    "compareWithAnotherWord": "Compare with another word",
    "showingOnlyEmotionalGroup": "Showing only emotional group",
    "emotionalGroup": "emotional group",
    "showingAllEmotionalGroups": "Showing all emotional groups",
    "viewReset": "View reset",
    "documentSummary": "Document Summary",
    "readMore": "Read More",
    "showLess": "Show Less",
    "noSummaryAvailable": "No summary available",
    "viewDetailedAnalysisData": "View Detailed Analysis Data",
    "analyzedWords": "Analyzed Words",
    "summary": "Summary",
    "textSample": "Text Sample",
    "viewFullText": "View Full Text",
    "fullText": "Full Text"
  },
  de: {
    "upload": "Hochladen",
    "darkMode": "Dunkelmodus",
    "lightMode": "Hellmodus",
    "selectFile": "Datei auswählen",
    "orDragDrop": "oder Drag & Drop",
    "journalEntry": "Tagebucheintrag",
    "perfectLife": "Perfektes Leben",
    "monthlyReflections": "Monatliche Reflexionen",
    "documentAnalysis": "Dokumentanalyse",
    "selectedFile": "Ausgewählte Datei",
    "noFileSelected": "Keine Datei ausgewählt",
    "analyzeWithBert": "Analysieren mit BERT",
    "analyzeWithGemma3": "Analysieren mit Gemma 3",
    "analysisResults": "Analyseergebnisse",
    "fileName": "Dateiname",
    "fileSize": "Dateigröße",
    "wordCount": "Wortanzahl",
    "latentEmotionalAnalysisTab": "Latente Emotionale Analyse",
    "overviewTab": "Überblick",
    "timelineTab": "Zeitleiste",
    "themesTab": "Themen",
    "keywordsTab": "Schlüsselwörter",
    "latentEmotionalAnalysis": "Latente Emotionale Analyse",
    "searchWordsOrEmotions": "Suche Wörter oder Emotionen",
    "resetView": "Ansicht zurücksetzen",
    "searchWords": "Suche Wörter",
    "noResultsFound": "Keine Ergebnisse gefunden",
    "hoverOrClick": "Bewegen Sie den Mauszeiger über einen Punkt oder klicken Sie darauf, um weitere Details anzuzeigen",
    "overallSentiment": "Gesamtstimmung",
    "positive": "Positiv",
    "neutral": "Neutral",
    "negative": "Negativ",
    "sentimentDistribution": "Stimmungsverteilung",
    "time": "Zeit",
    "event": "Ereignis",
    "entity": "Entität",
    "sentimentScore": "Stimmungsbewertung",
    "keyPhrase": "Schlüsselphrase",
    "occurrences": "Vorkommnisse",
    "relatedTerms": "Verwandte Begriffe",
    "visualSearch": "Visuelle Suche",
    "wellbeingResources": "Ressourcen für das Wohlbefinden",
    "compareWords": "Wörter vergleichen",
    "spatialSimilarity": "Räumliche Ähnlichkeit",
    "sentimentSimilarity": "Stimmungsähnlichkeit",
    "emotionalProximity": "Emotionale Nähe",
    "sharedKeywords": "Gemeinsame Schlüsselwörter",
    "submitEntry": "Eintrag einreichen",
    "pastEntries": "Vergangene Einträge",
    "noPastEntries": "Keine vergangenen Einträge verfügbar.",
    "addToMonthlyReflection": "Zu monatlicher Reflexion hinzufügen",
    "saveChanges": "Änderungen speichern",
    "daily": "Täglich",
    "weekly": "Wöchentlich",
    "monthly": "Monatlich",
    "perfectDay": "Wie sieht dein perfekter Tag aus?",
    "perfectWeek": "Wie sieht deine perfekte Woche aus?",
    "perfectMonth": "Wie sieht dein perfekter Monat aus?",
    "journalPrompt": "Schreibe über deinen Tag...",
    "journalCache": "Journal-Cache",
    "selectEntry": "Eintrag auswählen",
    "noDataTabName": "Keine Daten für den Tab {tabName} verfügbar.",
    "dataAvailableMissing": "Bitte stellen Sie sicher, dass die Dokumentanalyse abgeschlossen ist, um diesen Inhalt anzuzeigen.",
    "selected": "Ausgewählt",
    "neutral": "Neutral",
    "selectingComparison": "Vergleichspunkt auswählen...",
    "compareWithAnotherWord": "Mit einem anderen Wort vergleichen",
    "showingOnlyEmotionalGroup": "Zeige nur die emotionale Gruppe",
    "emotionalGroup": "emotionale Gruppe",
    "showingAllEmotionalGroups": "Zeige alle emotionalen Gruppen",
    "viewReset": "Ansicht zurückgesetzt",
    "documentSummary": "Dokumentzusammenfassung",
    "readMore": "Mehr lesen",
    "showLess": "Weniger zeigen",
    "noSummaryAvailable": "Keine Zusammenfassung verfügbar",
    "viewDetailedAnalysisData": "Detaillierte Analysedaten anzeigen",
    "analyzedWords": "Analysierte Wörter",
    "summary": "Zusammenfassung",
    "textSample": "Textprobe",
    "viewFullText": "Volltext anzeigen",
    "fullText": "Volltext"
  },
  es: {
    "upload": "Subir",
    "darkMode": "Modo Oscuro",
    "lightMode": "Modo Claro",
    "selectFile": "Seleccionar Archivo",
    "orDragDrop": "o Arrastrar y Soltar",
    "journalEntry": "Entrada de Diario",
    "perfectLife": "Vida Perfecta",
    "monthlyReflections": "Reflexiones Mensuales",
    "documentAnalysis": "Análisis de Documento",
    "selectedFile": "Archivo Seleccionado",
    "noFileSelected": "Ningún archivo seleccionado",
    "analyzeWithBert": "Analizar con BERT",
    "analyzeWithGemma3": "Analizar con Gemma 3",
    "analysisResults": "Resultados del Análisis",
    "fileName": "Nombre del Archivo",
    "fileSize": "Tamaño del Archivo",
    "wordCount": "Conteo de Palabras",
    "latentEmotionalAnalysisTab": "Análisis Emocional Latente",
    "overviewTab": "Resumen",
    "timelineTab": "Cronología",
    "themesTab": "Temas",
    "keywordsTab": "Palabras Clave",
    "latentEmotionalAnalysis": "Análisis Emocional Latente",
    "searchWordsOrEmotions": "Buscar Palabras o Emociones",
    "resetView": "Restablecer Vista",
    "searchWords": "Buscar Palabras",
    "noResultsFound": "No se encontraron resultados",
    "hoverOrClick": "Pasa el ratón o haz clic en un punto para ver más detalles",
    "overallSentiment": "Sentimiento General",
    "positive": "Positivo",
    "neutral": "Neutral",
    "negative": "Negativo",
    "sentimentDistribution": "Distribución de Sentimientos",
    "time": "Tiempo",
    "event": "Evento",
    "entity": "Entidad",
    "sentimentScore": "Puntuación de Sentimiento",
    "keyPhrase": "Frase Clave",
    "occurrences": "Ocurrencias",
    "relatedTerms": "Términos Relacionados",
    "visualSearch": "Búsqueda Visual",
    "wellbeingResources": "Recursos para el Bienestar",
    "compareWords": "Comparar Palabras",
    "spatialSimilarity": "Similitud Espacial",
    "sentimentSimilarity": "Similitud de Sentimientos",
    "emotionalProximity": "Proximidad Emocional",
    "sharedKeywords": "Palabras Clave Compartidas",
    "submitEntry": "Enviar Entrada",
    "pastEntries": "Entradas Anteriores",
    "noPastEntries": "No hay entradas anteriores disponibles.",
    "addToMonthlyReflection": "Añadir a la Reflexión Mensual",
    "saveChanges": "Guardar Cambios",
    "daily": "Diario",
    "weekly": "Semanal",
    "monthly": "Mensual",
    "perfectDay": "¿Cómo es tu día perfecto?",
    "perfectWeek": "¿Cómo es tu semana perfecta?",
    "perfectMonth": "¿Cómo es tu mes perfecto?",
    "journalPrompt": "Escribe sobre tu día...",
    "journalCache": "Caché del Diario",
    "selectEntry": "Seleccionar Entrada",
    "noDataTabName": "No hay datos disponibles para la pestaña {tabName}.",
    "dataAvailableMissing": "Asegúrate de que el análisis del documento esté completo para ver este contenido.",
    "selected": "Seleccionado",
    "neutral": "Neutral",
    "selectingComparison": "Seleccionando punto de comparación...",
    "compareWithAnotherWord": "Comparar con otra palabra",
    "showingOnlyEmotionalGroup": "Mostrando solo el grupo emocional",
    "emotionalGroup": "grupo emocional",
    "showingAllEmotionalGroups": "Mostrando todos los grupos emocionales",
    "viewReset": "Vista restablecida",
    "documentSummary": "Resumen del Documento",
    "readMore": "Leer Más",
    "showLess": "Mostrar Menos",
    "noSummaryAvailable": "No hay resumen disponible",
    "viewDetailedAnalysisData": "Ver Datos Detallados del Análisis",
    "analyzedWords": "Palabras Analizadas",
    "summary": "Resumen",
    "textSample": "Muestra de Texto",
    "viewFullText": "Ver Texto Completo",
    "fullText": "Texto Completo"
  }
};

const defaultLanguage = 'en';

const LanguageContext = createContext<LanguageContextType>({
  t: (key: string) => key,
  setLanguage: () => {},
  language: defaultLanguage
});

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState(defaultLanguage);
  
  const t = (key: string): string => {
    if (translations[language] && translations[language][key]) {
      return translations[language][key];
    }
    
    // Fallback to English
    if (translations[defaultLanguage] && translations[defaultLanguage][key]) {
      return translations[defaultLanguage][key];
    }
    
    // Fallback to the key itself
    return key;
  };
  
  return (
    <LanguageContext.Provider value={{ t, setLanguage, language }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
